### ISSUE TITLE
Investigate/Fix syntax error for duplicate Checksum aspect

### ISSUE THREAD

**Issue by mhadhbir** [AdaCore/RecordFlux-parser#56]
The following message is supposed to raise an error indicating a duplicate checksum aspect (once pull request Componolit/RecordFlux#930 is merged), but instead the langkit-based parser seems to raise a different error

`<stdin>:18:27: parser: error: Expected 'Byte_Order', got 'First'`

>                 package Test is
>                    type T is mod 2**8;
>                    type M is
>                       message
>                          F1 : T;
>                          F2 : T;
>                          C1 : T;
>                          F3 : T;
>                          C2 : T
>                             then F4
>                                if C1'Valid_Checksum and C2'Valid_Checksum;
>                          F4 : T;
>                       end message
>                          with Checksum => (C1 => (F3, F1'First .. F2'Last),
>                                            C2 => (C1'Last + 1 .. C2'First - 1)),
>                               Byte_Order => Low_Order_First,
>                               Checksum => (C1 => (F3, F1'First .. F2'Last),
>                                            C2 => (C1'Last + 1 .. C2'First - 1));
>                 end Test;

**Comment by treiher** [comment]
Moved into the RecordFlux-parser repository, as the problem is related to the langkit-based parser.
